/*  =========================================================================
    match - generated layer of public API

    Copyright (C) 2018 Gerald Guillaume

    This program is free software; you can redistribute it and/or modify

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef MATCH_LIBRARY_H_INCLUDED
#define MATCH_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  MATCH version macros for compile-time API detection
#define MATCH_VERSION_MAJOR 1
#define MATCH_VERSION_MINOR 0
#define MATCH_VERSION_PATCH 0

#define MATCH_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define MATCH_VERSION \
    MATCH_MAKE_VERSION(MATCH_VERSION_MAJOR, MATCH_VERSION_MINOR, MATCH_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined MATCH_STATIC
#       define MATCH_EXPORT
#   elif defined MATCH_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define MATCH_EXPORT __declspec(dllexport)
#       else
#           define MATCH_EXPORT
#       endif
#   elif defined MATCH_EXPORTS
#       define MATCH_EXPORT __declspec(dllexport)
#   else
#       define MATCH_EXPORT __declspec(dllimport)
#   endif
#   define MATCH_PRIVATE
#elif defined (__CYGWIN__)
#   define MATCH_EXPORT
#   define MATCH_PRIVATE
#else
#   define MATCH_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define MATCH_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define MATCH_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  MATCH_BUILD_DRAFT_API
#define MATCH_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef MATCH_BUILD_DRAFT_API
typedef struct _match_t match_t;
#define MATCH_T_DEFINED
#endif // MATCH_BUILD_DRAFT_API


//  Public classes, each with its own header file

#ifdef MATCH_BUILD_DRAFT_API
//  Self test for private classes
MATCH_EXPORT void
    match_private_selftest (bool verbose);
#endif // MATCH_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
