/*  =========================================================================
    match_classes - private header file

    Copyright (C) 2018 Gerald Guillaume

    This program is free software; you can redistribute it and/or modify

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef MATCH_CLASSES_H_INCLUDED
#define MATCH_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/match.h"

//  Extra headers

//  Opaque class structures to allow forward references

//  Internal API


//  *** To avoid double-definitions, only define if building without draft ***
#ifndef MATCH_BUILD_DRAFT_API

//  Self test for private classes
MATCH_PRIVATE void
    match_private_selftest (bool verbose);

#endif // MATCH_BUILD_DRAFT_API

#endif
